include(../../../main.cmake)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${APPPATH})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${RLIBRARYPATH})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${RLIBRARYPATH})

add_library(${PROJECT_NAME} STATIC ${HEADERS} ${SOURCES} ${FORMS} ${RESOURCES})

target_include_directories(${PROJECT_NAME}
    PUBLIC ${PROJECT_SOURCE_DIR}/include
)
