include(../../../main.cmake)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${APPPATH})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${RLIBRARYPATH})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${RLIBRARYPATH})

add_executable(${PROJECT_NAME} ${HEADERS} ${SOURCES} ${FORMS} ${RESOURCES})


